alias jira-add-comment="~/jira-python-utils/jira_add_comment.sh "
alias jira-assign-issue="~/jira-python-utils/jira_assign_issue.sh "
alias jira-get-issue-details="~/jira-python-utils/jira_get_issue_details.sh "
alias jira-remove-watcher="~/jira-python-utils/jira_remove_watcher.sh "
alias jira-create-issue="~/jira-python-utils/jira_create_issue.sh "
alias jira-add-change-control-comment="~/jira-python-utils/jira_add_change_control_comment.sh "
