echo "Will enable custom jira-python-utils aliases (in $0)"
alias jira-add-comment="~/.tools/jira-python-utils/jira_add_comment.sh "
alias jira-assign-issue="~/.tools/jira-python-utils/jira_assign_issue.sh "
alias jira-get-issue-details="~/.tools/jira-python-utils/jira_get_issue_details.sh "
alias jira-remove-watcher="~/.tools/jira-python-utils/jira_remove_watcher.sh "
alias jira-create-issue="~/.tools/jira-python-utils/jira_create_issue.sh "
alias jira-add-change-control-comment="~/.tools/jira-python-utils/jira_add_change_control_comment.sh "
alias jira-regenerate-confluence-epic-pages="~/.tools/jira-python-utils/jira_epics_to_confluence_tables.sh "
alias jira-generate-weekly-progress-pages="~/.tools/jira-python-utils/jira_to_confluence_weekly_progress_report.sh "
alias show-jira-python-utils-aliases="grep '^alias' $0 | grep -v show-jira-python-utils-aliases | sed 's/^alias //' | sed 's/=\"/ -> /' | sed 's/\"$//'"
