site_name: Jira Python Utils
# dev_addr: 127.0.0.1:8081
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      # python:
      handlers:
        python:
          paths: [jira_python_utils]
        # import_root: jira_python_utils
        # import_root: jira-python-utils
nav:
  - Home: index.md
  - Installation: INSTALL.md
  - Code Reference:
    - File Utililities: file_utils.md
