---
confluence:
  status:
    color_codes:
      done: "#00FF00"
      in_development: "#FF8300"
  space_key: "~jaideep.sundaram"
  rest_api_url: "https://confluence.regeneron.com/rest/api/content"
  parent_page_id: 406414536
  #318151621
  #"Jay's Weekly Progress Report"
  home_space: "https://confluence.regeneron.com/spaces/viewspace.action?key=~jaideep.sundaram"
jira:
  assignee: "jaideep.sundaram"
  issue_base_url: "https://jira.regeneron.com/browse/"
  weekly:
    # - start_date: 2023-01-06
    #   end_date: 2023-01-13
    # - start_date: 2023-01-13
    #   end_date: 2023-01-20
    # - start_date: 2023-01-20
    #   end_date: 2023-01-27
    # - start_date: 2023-01-27
    #   end_date: 2023-02-03
    # - start_date: 2023-02-03
    #   end_date: 2023-02-10
    # - start_date: 2023-02-10
    #   end_date: 2023-02-17
    # - start_date: 2023-02-10
    #   end_date: 2023-02-17
    # - start_date: 2023-02-17
    #   end_date: 2023-02-24
    #    - start_date: 2023-02-24
    #      end_date: 2023-03-03
    - start_date: 2023-03-03
      end_date: 2023-03-10
    - start_date: 2023-03-10
      end_date: 2023-03-17
    - start_date: 2023-03-17
      end_date: 2023-03-24
    - start_date: 2023-03-24
      end_date: 2023-03-31
    - start_date: 2023-03-31
      end_date: 2023-04-07
    - start_date: 2023-04-07
      end_date: 2023-04-14
    - start_date: 2023-04-14
      end_date: 2023-04-21
